name: LinuqBoxPVP
version: '1.2'
main: dev.linuq.linuqBoxPVP.LinuqBoxPVP
api-version: '1.18'
author: Linuqsior
description: Plugin na ustawiania boxpvp
commands:
  linuqboxpvp:
    permission: linuqboxpvp.admin