name: LinuqBoxPVP
version: '1.0'
main: dev.linuq.linuqBoxPVP.LinuqBoxPVP
api-version: '1.18'
authors: [ Linuqsior ]
description: Plugin na ustawiania boxpvp
commands:
  linuqboxpvp:
    permission: linuqboxpvp.admin